language: node_js
node_js:
  - 'lts/*'
  - 'node'
env:
  global:
    secure: gBK0zHhjzSmVHWe5DN0ZkJC8JA7RD7XBnH5GhYsDfiK0TpONHfIG6LIV1IM3AoBqkrO3paxsR0m9IWCeX3TsGc54zfT1s6lvwBB95HFukmX8fGdVP0oHXOpRnh4DddYJ7bBWM6UymFowehyMniAUbqPA7ouCCdcUuA3tfTbpQQAykZ4ZVZJdBCKqjgr8ni53OFVHeHenediq7oP6Lm8+/t80Bbi8scX/kV3RM6pnBr6BzwENFB4yvZozxPqidQaVay/83kgepkIyMBxayCC4VOcsBzfh7jVhKEakeTrsI1eG/09Jblf/n336DoM8PrISsGsi3EQCBA6LvouxhNJp6QE+AQE8e8rgELu+1GGGfylpxksFfRmRzooXeXQAs8m4jLGAGIij7N7Y9uq4zvfRPVF3mSBj4QfRv47U6Z3A6B6mR2uULLXkG4ju/3vNa27Vp6YXk+ocN/mzKNjjWvVDeMOntcVgh1zfo+VZAjJiflvKjccNVkfZLG54PX2Cbln0ets9qY7Bq53FtRyZkz9e5eOMHJFAvK/qX6HyqE2Z5Lp04eiFVddVCjf+/089hokKV4FF776CZA2MAhi3EDjbfi8uZggsbq6JtaJtlSOhxKdcQCkOPklyq5nKLrGnJC6UMjD5D/pieCjmfhwYt4mh1lJeYIV2jBuJOByTjksPRzs=
